default:
    command:
        history:
            filename: ../../cmdhist.pcap
        port: 3075

    cmddict:
        filename:  cmd.yaml

    tlmdict:
        filename:  tlm.yaml

    leapseconds:
        filename: leapseconds.dat

    phase: 'dev'

    server:
        plugins:
            - plugin:
                name: ait.gui.AITGUIPlugin
                inputs:
                    - telem_stream
                outputs:
                    - command_stream
                html:
                    directory: ../gui

        inbound-streams:
            - stream:
                name: telem_stream
                input:
                    - UDP
                    - "0.0.0.0"
                    - 5013
                handlers:
                    - name: ait.core.server.handlers.PacketHandler
                      packet: CFE_EVS_PACKET

        outbound-streams:
            - stream:
                name: command_stream
                output:
                    - "UDP"
                    - "nos_fsw"
                    - 5012
                command_subscriber: True
