default:
    command:
        history:
            filename: ../../cmdhist.pcap
        port: 3075

    cmddict:
        filename:  cmd.yaml

    tlmdict:
        filename:  tlm.yaml

    logging:
        name: ait
        hostname: yourCustomHostForLogging

    leapseconds:
        filename: leapseconds.dat

    phase: 'dev'

    server:
        plugins:
            - plugin:
                name: ait.gui.AITGUIPlugin
                inputs:
                    - log_stream
                    - telem_stream
                outputs:
                    - command_stream
                html:
                    directory: ../gui

        inbound-streams:
            - stream:
                name: log_stream
                input:
                    - 2514

            - stream:
                name: telem_stream
                input:
                    - 3076
                handlers:
                    - name: ait.core.server.handlers.PacketHandler
                      packet: CFE_EVS_PACKET

        outbound-streams:
            - stream:
                name: command_stream
                output: 3075
                command_subscriber: True
