- !include NAV_TLM.yaml
- !include CFE_ES_HKPACKET.yaml
- !include CFE_EVS_PACKET.yaml
- !include CFE_EVS_TLMPKT.yaml
- !include CFE_HK_PKT.yaml
- !include CFE_HK_COMBINED_PKT1.yaml
- !include CFE_SB_HKMSG.yaml
- !include CFE_TBL_HKPACKET.yaml
- !include CFE_TIME_HKPACKET.yaml

